version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: mkdir dist
      - run: ls
      - run: npm i
      - run: npm i typescript
      - run: npm run build
      - run: npm run test
workflows:
  run-test:
    jobs:
      - test
