version: 2.1

orbs:
  node: circleci/node@5.0.3

workflows:
    test-workflow:
      jobs:
        - test
            
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: npm i
      - run: npm i typescript
      - run: npm run build
      - run: npm run test 
