name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify a Node.js version
      - name: Install dependencies
        run: npm i
      - name: Install TypeScript
        run: npm i typescript --save-dev # Save as dev dependency
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
